[package]
name = "malai"
version = "0.2.1"
authors.workspace = true
edition.workspace = true
description = "malai: Kulfi Network Toolkit"
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

[features]
ui = ["tauri", "tauri-plugin-opener", "tauri-build"]

[dependencies]
clap-verbosity-flag.workspace = true
clap.workspace = true
colored.workspace = true
eyre.workspace = true
http-body-util.workspace = true
hyper-util.workspace = true
hyper.workspace = true
iroh.workspace = true
kulfi-utils.workspace = true
rand.workspace = true
serde_json.workspace = true
tauri-plugin-opener = { workspace = true, optional = true }
tauri = { workspace = true, optional = true }
tokio-stream.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
tokio-util.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libdbus-sys.workspace = true


[build-dependencies]
tauri-build = { workspace = true, optional = true }
